<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1488790821077" stop="1488790836422">
	<name>Validate Footer</name>
	<title>Validate Footer</title>
	<test-cases>
		<test-case start="1488790821078" stop="1488790834983" status="passed">
			<name>Loading Home Page </name>
			<title>Loading Home Page </title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="808ccffc-2953-45e9-920f-a4d120eb45ed-attachment.png" type="image/png" size="322367"/>
			</attachments>
		</test-case>
		<test-case start="1488790834983" stop="1488790835203" status="passed">
			<name>Validate Correct page Loaded</name>
			<title>Validate Correct page Loaded</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="3f6cee2b-d90c-45dd-9b56-ac55d26e969a-attachment.png" type="image/png" size="314307"/>
			</attachments>
		</test-case>
		<test-case start="1488790835203" stop="1488790836421" status="failed">
			<name>Footer links Validation</name>
			<title>Footer links Validation</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="b2d5c655-a28d-4073-9de2-3733680c14a9-attachment.png" type="image/png" size="90060"/>
			</attachments>
			<failure>
				<message>Expected undefined to equal &apos;https://apex-qa.phenompro.com/&apos;, &apos;Expected and actual href values of social sharing in footer are not matching&apos;.</message>
				<stack-trace>Error: Failed expectation
    at dummy (E:\protractorcms\cyborg\features\FT\FT-001\FT-001.js:58:50)
    at E:\protractorcms\cyborg\features\FT\FT-001\FT-001.js:25:17
    at ManagedPromise.invokeCallback_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
    at TaskQueue.execute_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    at C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>