<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1488793106302" stop="1488793116440">
	<name>Validate Footer</name>
	<title>Validate Footer</title>
	<test-cases>
		<test-case start="1488793106303" stop="1488793114898" status="passed">
			<name>Loading Home Page </name>
			<title>Loading Home Page </title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="73809484-4463-4239-8bd3-07bafa852c31-attachment.png" type="image/png" size="322367"/>
			</attachments>
		</test-case>
		<test-case start="1488793114899" stop="1488793115189" status="passed">
			<name>Validate Correct page Loaded</name>
			<title>Validate Correct page Loaded</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="4dd655e3-837a-46c5-8fd2-cb9810c815bc-attachment.png" type="image/png" size="314307"/>
			</attachments>
		</test-case>
		<test-case start="1488793115190" stop="1488793116440" status="failed">
			<name>Footer links Validation</name>
			<title>Footer links Validation</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="de1b12df-adf7-4c2b-8183-682c05d625cf-attachment.png" type="image/png" size="90060"/>
			</attachments>
			<failure>
				<message>Expected undefined to equal &apos;https://apex-qa.phenompro.com/&apos;, &apos;Expected and actual href values of social sharing in footer are not matching&apos;.</message>
				<stack-trace>Error: Failed expectation
    at dummy (E:\protractorcms\cyborg\features\FT\FT-001\FT-001.js:59:50)
    at E:\protractorcms\cyborg\features\FT\FT-001\FT-001.js:25:17
    at ManagedPromise.invokeCallback_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
    at TaskQueue.execute_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    at C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>