<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1488790354633" stop="1488790364111">
	<name>Validate Footer</name>
	<title>Validate Footer</title>
	<test-cases>
		<test-case start="1488790354634" stop="1488790362656" status="passed">
			<name>Loading Home Page </name>
			<title>Loading Home Page </title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="7fcdc033-10f0-4554-97b8-ad9c0b684c55-attachment.png" type="image/png" size="322367"/>
			</attachments>
		</test-case>
		<test-case start="1488790362656" stop="1488790362898" status="passed">
			<name>Validate Correct page Loaded</name>
			<title>Validate Correct page Loaded</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="7b40955c-7324-4a65-8e28-c91fed552fc9-attachment.png" type="image/png" size="314307"/>
			</attachments>
		</test-case>
		<test-case start="1488790362898" stop="1488790364111" status="failed">
			<name>Footer links Validation</name>
			<title>Footer links Validation</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="a2beb432-4147-42fa-abcc-4c95dfd791e1-attachment.png" type="image/png" size="90060"/>
			</attachments>
			<failure>
				<message>Expected undefined to equal &apos;https://apex-qa.phenompro.com/&apos;, &apos;Expected and actual href values of social sharing in footer are not matching&apos;.</message>
				<stack-trace>Error: Failed expectation
    at dummy (E:\protractorcms\cyborg\features\FT\FT-001\FT-001.js:58:50)
    at E:\protractorcms\cyborg\features\FT\FT-001\FT-001.js:25:17
    at ManagedPromise.invokeCallback_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
    at TaskQueue.execute_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    at C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>