<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1488790586784" stop="1488790597808">
	<name>Validate Footer</name>
	<title>Validate Footer</title>
	<test-cases>
		<test-case start="1488790586785" stop="1488790596337" status="passed">
			<name>Loading Home Page </name>
			<title>Loading Home Page </title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="30096ad3-9a34-4ec3-a6c0-eb70c938a8fa-attachment.png" type="image/png" size="322367"/>
			</attachments>
		</test-case>
		<test-case start="1488790596337" stop="1488790596584" status="passed">
			<name>Validate Correct page Loaded</name>
			<title>Validate Correct page Loaded</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="a60cfa8a-0e81-4cbb-a361-a90aa95b6ad0-attachment.png" type="image/png" size="314307"/>
			</attachments>
		</test-case>
		<test-case start="1488790596585" stop="1488790597808" status="failed">
			<name>Footer links Validation</name>
			<title>Footer links Validation</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="0fbfac93-355e-454f-a7b5-2be2622b0306-attachment.png" type="image/png" size="90060"/>
			</attachments>
			<failure>
				<message>Expected &apos;[object Object]&apos; to equal &apos;https://apex-qa.phenompro.com/&apos;, &apos;Expected and actual href values of social sharing in footer are not matching&apos;.</message>
				<stack-trace>Error: Failed expectation
    at dummy (E:\protractorcms\cyborg\features\FT\FT-001\FT-001.js:58:50)
    at E:\protractorcms\cyborg\features\FT\FT-001\FT-001.js:25:17
    at ManagedPromise.invokeCallback_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
    at TaskQueue.execute_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    at C:\Users\Ravikiran\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>